# Generated by Django 5.0.1 on 2024-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
    ]
